#!/bin/bash
set -ex

if [ "$DOCKER_TAG" == latest ]; then
    for version in $(cat versions); do
        docker build \
            --build-arg "version=$version" \
            --tag "$DOCKER_REPO:$version" .
    done
fi
